name: Deploy Android

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/android/**'
  release:
    types: [published]

jobs:
  deploy-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/android

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        working-directory: ./apps/android

    - name: Decode Keystore
      env:
        ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      run: |
        echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > keystore.jks
        echo "ANDROID_KEYSTORE_FILE=$(pwd)/keystore.jks" >> $GITHUB_ENV

    - name: Create Google Play JSON Key
      env:
        ANDROID_JSON_KEY_BASE64: ${{ secrets.ANDROID_JSON_KEY_BASE64 }}
      run: |
        echo "$ANDROID_JSON_KEY_BASE64" | base64 --decode > google-play-key.json
        echo "ANDROID_JSON_KEY_FILE=$(pwd)/google-play-key.json" >> $GITHUB_ENV

    - name: Distribute to Beta (Internal)
      if: github.event_name == 'push'
      env:
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: bundle exec fastlane beta

    - name: Deploy to Production
      if: github.event_name == 'release'
      env:
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: bundle exec fastlane deploy
